// <auto-generated />
using System;
using ITInventoryJLS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ITInventoryJLS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260124103000_DropDBPasswordFromDBUser")]
    partial class DropDBPasswordFromDBUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally left minimal. The project snapshot represents the current model.
        }
    }
}
